import '../models/product.dart';

class MockData {
  static final List<Product> products = [
    // Rings
    Product(
      id: '1',
      name: 'Diamond Solitaire Ring',
      description: 'A stunning solitaire diamond ring set in 18K white gold. The center stone is a brilliant cut diamond with exceptional clarity and sparkle.',
      price: 85000,
      originalPrice: 100000,
      images: [
        'https://images.unsplash.com/photo-1605100804763-247f67b3557e',
        'https://images.unsplash.com/photo-1603561591411-07134e71a2a9',
      ],
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      category: 'Rings',
      subcategory: 'Engagement',
      metalType: '18K White Gold',
      stoneType: 'Diamond',
      weight: 3.5,
      size: '6',
      stockQuantity: 5,
      rating: 4.8,
      reviewCount: 124,
      tags: ['diamond', 'engagement', 'solitaire'],
      isFeatured: true,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    Product(
      id: '2',
      name: 'Rose Gold Eternity Band',
      description: 'Delicate eternity band featuring lab-grown diamonds set in rose gold. Perfect for stacking or wearing alone.',
      price: 35000,
      images: [
        'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1',
      ],
      category: 'Rings',
      subcategory: 'Wedding',
      metalType: '14K Rose Gold',
      stoneType: 'Lab Diamond',
      weight: 2.8,
      size: '7',
      stockQuantity: 8,
      rating: 4.6,
      reviewCount: 89,
      tags: ['rose gold', 'wedding', 'eternity'],
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
    ),

    // Necklaces
    Product(
      id: '3',
      name: 'Pearl Strand Necklace',
      description: 'Classic Akoya pearl necklace with 18K gold clasp. Each pearl is hand-selected for its luster and quality.',
      price: 55000,
      originalPrice: 65000,
      images: [
        'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f',
      ],
      category: 'Necklaces',
      subcategory: 'Pearl',
      metalType: '18K Yellow Gold',
      stoneType: 'Pearl',
      weight: 45,
      stockQuantity: 3,
      rating: 4.9,
      reviewCount: 156,
      tags: ['pearl', 'classic', 'elegant'],
      isFeatured: true,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
    ),
    Product(
      id: '4',
      name: 'Layered Gold Chain',
      description: 'Modern layered chain necklace in yellow gold. Features three delicate chains of varying lengths.',
      price: 28000,
      images: [
        'https://images.unsplash.com/photo-1611591437281-460bfbe1220a',
      ],
      category: 'Necklaces',
      subcategory: 'Chain',
      metalType: '14K Yellow Gold',
      weight: 12,
      stockQuantity: 10,
      rating: 4.5,
      reviewCount: 67,
      tags: ['layered', 'trendy', 'minimalist'],
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
    ),

    // Earrings
    Product(
      id: '5',
      name: 'Diamond Stud Earrings',
      description: 'Classic diamond studs featuring brilliant cut diamonds in a four-prong setting.',
      price: 42000,
      images: [
        'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908',
      ],
      category: 'Earrings',
      subcategory: 'Studs',
      metalType: '18K White Gold',
      stoneType: 'Diamond',
      weight: 2.0,
      stockQuantity: 6,
      rating: 4.7,
      reviewCount: 203,
      tags: ['diamond', 'studs', 'classic'],
      isFeatured: true,
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
    ),
    Product(
      id: '6',
      name: 'Emerald Drop Earrings',
      description: 'Elegant emerald drop earrings with diamond accents. Perfect for special occasions.',
      price: 68000,
      originalPrice: 75000,
      images: [
        'https://images.unsplash.com/photo-1573408301185-9146fe634ad0',
      ],
      category: 'Earrings',
      subcategory: 'Drop',
      metalType: '18K Yellow Gold',
      stoneType: 'Emerald',
      weight: 4.5,
      stockQuantity: 2,
      rating: 4.8,
      reviewCount: 92,
      tags: ['emerald', 'luxury', 'statement'],
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
    ),

    // Bracelets
    Product(
      id: '7',
      name: 'Tennis Bracelet',
      description: 'Timeless tennis bracelet featuring a continuous line of diamonds set in white gold.',
      price: 95000,
      images: [
        'https://images.unsplash.com/photo-1611652022419-a9419f74343d',
      ],
      category: 'Bracelets',
      subcategory: 'Tennis',
      metalType: '18K White Gold',
      stoneType: 'Diamond',
      weight: 15,
      stockQuantity: 4,
      rating: 4.9,
      reviewCount: 178,
      tags: ['tennis', 'diamond', 'luxury'],
      isFeatured: true,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
    Product(
      id: '8',
      name: 'Gold Bangle Set',
      description: 'Set of three textured gold bangles. Mix and match or wear together for a bold look.',
      price: 45000,
      images: [
        'https://images.unsplash.com/photo-1573408301185-9146fe634ad0',
      ],
      category: 'Bracelets',
      subcategory: 'Bangle',
      metalType: '22K Yellow Gold',
      weight: 35,
      stockQuantity: 7,
      rating: 4.4,
      reviewCount: 56,
      tags: ['bangle', 'traditional', 'gold'],
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
    ),

    // More products...
    Product(
      id: '9',
      name: 'Ruby Pendant Necklace',
      description: 'Stunning ruby pendant surrounded by diamonds on a delicate gold chain.',
      price: 52000,
      originalPrice: 60000,
      images: [
        'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338',
      ],
      category: 'Necklaces',
      subcategory: 'Pendant',
      metalType: '18K Yellow Gold',
      stoneType: 'Ruby',
      weight: 8,
      stockQuantity: 3,
      rating: 4.7,
      reviewCount: 134,
      tags: ['ruby', 'pendant', 'gemstone'],
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Product(
      id: '10',
      name: 'Platinum Wedding Band',
      description: 'Classic platinum wedding band with a comfort fit design.',
      price: 38000,
      images: [
        'https://images.unsplash.com/photo-1602752549508-e5338093db7f',
      ],
      category: 'Rings',
      subcategory: 'Wedding',
      metalType: 'Platinum',
      weight: 6,
      size: '8',
      stockQuantity: 12,
      rating: 4.6,
      reviewCount: 98,
      tags: ['platinum', 'wedding', 'mens'],
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
  ];

  static final List<String> categories = [
    'All',
    'Rings',
    'Necklaces',
    'Earrings',
    'Bracelets',
    'Watches',
  ];

  static final Map<String, String> categoryImages = {
    'Rings': 'https://images.unsplash.com/photo-1605100804763-247f67b3557e',
    'Necklaces': 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f',
    'Earrings': 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908',
    'Bracelets': 'https://images.unsplash.com/photo-1611652022419-a9419f74343d',
    'Watches': 'https://images.unsplash.com/photo-1524592094714-0f0654e20314',
  };

  static final List<Map<String, String>> banners = [
    {
      'image': 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338',
      'title': 'New Collection',
      'subtitle': 'Discover our latest designs',
    },
    {
      'image': 'https://images.unsplash.com/photo-1605100804763-247f67b3557e',
      'title': 'Diamond Sale',
      'subtitle': 'Up to 30% off on select pieces',
    },
    {
      'image': 'https://images.unsplash.com/photo-1611652022419-a9419f74343d',
      'title': 'Bridal Collection',
      'subtitle': 'Find your perfect wedding jewelry',
    },
  ];

  static final List<Review> reviews = [
    Review(
      id: '1',
      userId: '1',
      userName: 'Priya Sharma',
      productId: '1',
      rating: 5,
      comment: 'Absolutely stunning ring! The diamond sparkles beautifully and the quality is exceptional.',
      images: [],
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Review(
      id: '2',
      userId: '2',
      userName: 'Rahul Verma',
      productId: '1',
      rating: 4,
      comment: 'Great quality but slightly expensive. The craftsmanship is excellent though.',
      images: [],
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
  ];
}